name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Choose the environment
        options:
          - DEV
          # - PROD
        required: true

jobs:
  deploy_dev:
    name: Deploy to DEV
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy
        uses: ./.github/actions/deploy
        with:
          AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
          AWS_DEFAULT_REGION: ${{ vars.REGION }}
          ENVIRONMENT: ${{ inputs.environment }}
